### ISSUE TITLE
Source for 0.0.6 of this cookbook on the Supermarket different than repo?

### ISSUE THREAD

**Issue by duro** [ismell/docker-registry-cookbook#18]
I pulled this cookbook from the Supermarket, and the config file template that comes down looks like this:

```
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    storage: <%= @storage %>
    storage_path: <%= @storage_path %>
    secret_key: <%= @secret_key %>
    <% if @storage == "s3" -%>
    s3_access_key: <%= @s3_access_key %>
    s3_secret_key: <%= @s3_secret_key %>
    s3_bucket: <%= @s3_bucket %>
    <% end %>

    standalone: <%= @standalone %>
    <% unless @standalone %>
    index_endpoint: <%= @index_endpoint %>
    <% end %>

# This is the default configuration when no flavor is specified
dev:
    loglevel: debug

prod:
    loglevel: warn
```

However, in this repo it looks like this:

```
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    storage: <%= @storage %>
    storage_path: <%= @storage_path %>
    secret_key: <%= @secret_key %>
    <% if @storage == "s3" -%>
    s3_access_key: <%= @s3_access_key %>
    s3_secret_key: <%= @s3_secret_key %>
    s3_bucket: <%= @s3_bucket %>
    boto_bucket: <%= @s3_bucket %>
    <% end %>

    standalone: <%= @standalone %>
    <% unless @standalone %>
    index_endpoint: <%= @index_endpoint %>
    <% end %>

# This is the default configuration when no flavor is specified
dev:
    loglevel: debug

prod:
    loglevel: warn
```
